# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Mini import*
from Mining1 import*
from power_mining import*


class Ui_MainWindow(object):

    # Action method for NMZ button.
    def openNMZScripts(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_NMZ()
        self.ui.setupUi(self.window)
        self.window.show()
    
    # Action method for Mining skill.
    def openMining1(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Mining1()
        self.ui.setupUi(self.window)
        self.window.show()

    # Action method for PowerMining button.
    def startPowerMining(self):
        miningScript()


        
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(271, 387)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 80, 71, 41))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(30, 280, 71, 41))
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.Fletching = QtWidgets.QPushButton(self.centralwidget)
        self.Fletching.setGeometry(QtCore.QRect(100, 200, 71, 41))
        self.Fletching.setStyleSheet("QPushButton {\n"
"            background: grey;\n"
"            image: url(skill_icons/Fletching_icon.png);\n"
"        }")
        self.Fletching.setText("")
        self.Fletching.setObjectName("Fletching")
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setGeometry(QtCore.QRect(40, 330, 41, 31))
        self.pushButton_31.setText("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.Thieving = QtWidgets.QPushButton(self.centralwidget)
        self.Thieving.setGeometry(QtCore.QRect(100, 120, 71, 41))
        self.Thieving.setStyleSheet("QPushButton {\n"
"            background: grey;\n"
"            image: url(skill_icons/Thieving_icon.png);\n"
"        }")
        self.Thieving.setText("")
        self.Thieving.setObjectName("Thieving")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(100, 160, 71, 41))
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.Mining = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openMining1())
        self.Mining.setGeometry(QtCore.QRect(170, 0, 71, 41))
        self.Mining.setStyleSheet("QPushButton {\n"
"            background: grey;\n"
"            image: url(skill_icons/Mining_icon.png);\n"
"        }")
        self.Mining.setText("")
        self.Mining.setObjectName("Mining")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(100, 0, 71, 41))
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(200, 330, 41, 31))
        self.pushButton_27.setText("")
        self.pushButton_27.setObjectName("pushButton_27")
        self.Cooking = QtWidgets.QPushButton(self.centralwidget)
        self.Cooking.setGeometry(QtCore.QRect(170, 120, 71, 41))
        self.Cooking.setStyleSheet("QPushButton {\n"
"            background: grey;\n"
"            image: url(skill_icons/Cooking icon.png);\n"
"        }")
        self.Cooking.setText("")
        self.Cooking.setObjectName("Cooking")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(30, 240, 71, 41))
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(170, 280, 71, 41))
        self.pushButton_23.setStyleSheet("QPushButton {\n"
"            background: black;\n"
"             color : yellow; \n"
"    font-size: 10px\n"
"            \n"
"        }\n"
"")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(100, 40, 71, 41))
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.Prayer = QtWidgets.QPushButton(self.centralwidget)
        self.Prayer.setGeometry(QtCore.QRect(30, 160, 71, 41))
        self.Prayer.setStyleSheet("QPushButton {\n"
"            background: grey;\n"
"            image: url(skill_icons/Prayer icon.png);\n"
"        }")
        self.Prayer.setText("")
        self.Prayer.setObjectName("Prayer")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 40, 71, 41))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(170, 160, 71, 41))
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 0, 71, 41))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 0, 20, 321))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(100, 280, 71, 41))
        self.pushButton_24.setText("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setGeometry(QtCore.QRect(80, 330, 41, 31))
        self.pushButton_30.setText("")
        self.pushButton_30.setObjectName("pushButton_30")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(250, 0, 20, 321))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(170, 80, 71, 41))
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(100, 240, 71, 41))
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setGeometry(QtCore.QRect(160, 330, 41, 31))
        self.pushButton_28.setText("")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 120, 71, 41))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(170, 240, 71, 41))
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 80, 71, 41))
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.Smithing = QtWidgets.QPushButton(self.centralwidget)
        self.Smithing.setGeometry(QtCore.QRect(170, 40, 71, 41))
        self.Smithing.setStyleSheet("QPushButton {\n"
"            background: grey;\n"
"            image: url(skill_icons/Smithing_icon.png);\n"
"        }")
        self.Smithing.setText("")
        self.Smithing.setObjectName("Smithing")
        
        self.NMZ = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openNMZScripts())
        self.NMZ.setGeometry(QtCore.QRect(0, 330, 41, 31))
        self.NMZ.setStyleSheet("QPushButton {\n"
        "            background: grey;\n"
"            image: url(skill_icons/Grouping icon.png);\n"
"        }")
        self.NMZ.setText("")
        self.NMZ.setObjectName("NMZ")
        # Adding action to button
        self.NMZ.clicked.connect(self.openNMZScripts)


        
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setGeometry(QtCore.QRect(120, 330, 41, 31))
        self.pushButton_29.setText("")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(240, 330, 41, 31))
        self.pushButton_26.setText("")
        self.pushButton_26.setObjectName("pushButton_26")
        self.Magic = QtWidgets.QPushButton(self.centralwidget)
        self.Magic.setGeometry(QtCore.QRect(30, 200, 71, 41))
        self.Magic.setStyleSheet("QPushButton {\n"
"            background: grey;\n"
"            image: url(skill_icons/Magic_icon.png);\n"
"        }")
        self.Magic.setText("")
        self.Magic.setObjectName("Magic")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(170, 200, 71, 41))
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 271, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyOSRSCheats"))
        self.pushButton_23.setText(_translate("MainWindow", "Total level:"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
